Repository Holzhaus/rekordcrate, pull requests merged in 2022-02, with the labels that each got.

#1 Implement parser for the PDB file format
  .gitattributes
  Cargo.lock
  Cargo.toml
  data/demo-tracks/PIONEER/DEVSETTING.DAT
  data/demo-tracks/PIONEER/DJMMYSETTING.DAT
  data/demo-tracks/PIONEER/MYSETTING.DAT
  data/demo-tracks/PIONEER/MYSETTING2.DAT
  data/demo-tracks/PIONEER/USBANLZ/P016/0000875E/ANLZ0000.2EX
  data/demo-tracks/PIONEER/USBANLZ/P016/0000875E/ANLZ0000.DAT
  data/demo-tracks/PIONEER/USBANLZ/P016/0000875E/ANLZ0000.EXT
  data/demo-tracks/PIONEER/USBANLZ/P053/0001D21F/ANLZ0000.2EX
  data/demo-tracks/PIONEER/USBANLZ/P053/0001D21F/ANLZ0000.DAT
  data/demo-tracks/PIONEER/USBANLZ/P053/0001D21F/ANLZ0000.EXT
  data/demo-tracks/PIONEER/rekordbox/export.pdb
  data/demo-tracks/PIONEER/rekordbox/exportExt.pdb
  data/empty/PIONEER/DEVSETTING.DAT
  data/empty/PIONEER/DJMMYSETTING.DAT
  data/empty/PIONEER/MYSETTING.DAT
  data/empty/PIONEER/MYSETTING2.DAT
  data/empty/PIONEER/rekordbox/export.pdb
  data/empty/PIONEER/rekordbox/exportExt.pdb
  src/lib.rs
  src/main.rs
  src/pdb.rs
Labels: enhancement

#2 Add basic ANLZ parser
  src/anlz.rs
  src/bin/rekordcrate-anlz.rs
  src/bin/rekordcrate-pdb.rs
  src/lib.rs
Labels: enhancement

#3 anlz: Implement section parsers
  .codespellignore
  src/anlz.rs
  src/lib.rs
  src/pdb.rs
  src/util.rs
Labels: enhancement

#19 anlz: Fix `ExtendedCue` color table in comment
  src/anlz.rs
Labels: documentation

#20 pdb.rs: Fix Table RowGroup parsing
  src/pdb.rs
Labels: bug

#29 anlz: Document that these files also exist when not using device exports
  src/anlz.rs
Labels: documentation

#28 pdb.rs: fix `DeviceSQLString::parse_long_utf16le` and `DeviceSQLString::parse_long_ascii`
  src/pdb.rs
Labels: bug

#24 pdb.rs: implement proper PageIndex iteration
  src/bin/rekordcrate-pdb.rs
  src/pdb.rs
  tests/tests_pdb.rs.in
Labels: bug

#26 pdb.rs: implement ISRC-string parsing
  src/pdb.rs
Labels: bug

#33 Fix length checks
  src/anlz.rs
Labels: bug

#42 Fix some `*SETTING.DAT` parser issues
  src/setting.rs
Labels: bug
